[alias]
c_reqwest_server = "run --package c_reqwest_server"
guide = "doc --open --no-deps --lib --document-private-items"
xtask = "run --package xtask"

[build]
rustdocflags = ["--html-in-header", "assets/katex-header.html"]
